/**
 * AUTO-GENERATED by web/app/scripts/generate-perf-moves.mjs — DO NOT EDIT.
 * 绝招数据来自 kungfu/skill/<id>/ 动作目录；动作名以 perform <slot>.<action> 使用。
 */
export interface PerfAction {
  /** perform <slot>.<action> 中的 action 段 */
  action: string;
  /** 绝招中文名 */
  name: string;
}
export interface PerfSkill {
  /** 武功中文名 */
  name: string;
  actions: PerfAction[];
}
export const PERF_MOVES: Record<string, PerfSkill> = {
  "banruo-zhang": { name: "般若掌", actions: [
    { action: "san", name: "一拍两散" },
  ] },
  "canhe-zhi": { name: "参合指", actions: [
    { action: "canshang", name: "动静如参商" },
  ] },
  "dagou-bang": { name: "打狗棒法", actions: [
    { action: "ban", name: "绊" },
    { action: "chan", name: "缠" },
    { action: "dagou", name: "打狗阵法" },
    { action: "duo", name: "獒口夺杖" },
    { action: "feng", name: "封字诀" },
    { action: "sansha", name: "三记杀招" },
    { action: "zhuan", name: "转字诀" },
  ] },
  "damo-jian": { name: "达摩剑", actions: [
    { action: "weituo", name: "韦陀伏魔剑" },
  ] },
  "douzhuan-xingyi": { name: "斗转星移", actions: [
    { action: "attack", name: "attack" },
    { action: "bidu", name: "bidu" },
    { action: "huxin", name: "护心功" },
  ] },
  "duanjia-jian": { name: "段家剑法", actions: [
    { action: "ailao", name: "哀牢山剑意" },
    { action: "yiyang", name: "一阳指力" },
  ] },
  "duanyun-bian": { name: "断云鞭", actions: [
    { action: "duanyun", name: "断云鞭" },
    { action: "riyue", name: "日月无光" },
  ] },
  "dugu-jiujian": { name: "独孤九剑", actions: [
    { action: "po", name: "总诀式" },
    { action: "pobian", name: "破鞭式" },
    { action: "podao", name: "破刀式" },
    { action: "pojian", name: "破剑式" },
    { action: "poqi", name: "破气式" },
    { action: "poqiang", name: "破枪式" },
    { action: "posuo", name: "破索式" },
    { action: "pozhang", name: "破掌式" },
  ] },
  "emei-jian": { name: "峨眉剑法", actions: [
    { action: "jue", name: "绝剑" },
    { action: "mie", name: "灭剑" },
  ] },
  "feifeng-bian": { name: "飞凤鞭法", actions: [
    { action: "jiutian", name: "凤舞九天" },
  ] },
  "feiyu-bian": { name: "飞羽鞭法", actions: [
    { action: "chanrao", name: "缠绕" },
    { action: "heji", name: "合击" },
  ] },
  "fengmo-zhang": { name: "疯魔杖法", actions: [
    { action: "feizhang", name: "疯魔飞杖" },
    { action: "fengmo", name: "疯魔飞杖" },
  ] },
  "huashan-jianfa": { name: "华山剑法", actions: [
    { action: "feilong", name: "天外飞龙" },
    { action: "jianzhang", name: "剑掌五连环" },
  ] },
  "huifeng-jian": { name: "回风拂柳剑", actions: [
    { action: "jue", name: "绝剑" },
    { action: "mie", name: "灭剑" },
  ] },
  "hunyuan-zhang": { name: "混元掌", actions: [
    { action: "leidong", name: "雷动九天" },
    { action: "wuji", name: "混元无极" },
  ] },
  "huoyan-dao": { name: "火焰刀", actions: [
    { action: "fen", name: "焚" },
  ] },
  "jinding-zhang": { name: "金顶绵掌", actions: [
    { action: "piaoxue", name: "飘雪穿云掌" },
    { action: "puzhao", name: "佛光普照" },
  ] },
  "jingang-quan": { name: "金刚拳", actions: [
    { action: "jingang", name: "金刚神通" },
  ] },
  "jinshe-zhuifa": { name: "金蛇锥法", actions: [
    { action: "huayu", name: "漫天花雨" },
    { action: "tuwu", name: "金蛇吐雾" },
  ] },
  "jiuyin-zhao": { name: "九阴神爪", actions: [
    { action: "shenzhua", name: "九阴神爪" },
  ] },
  "jueming-tui": { name: "绝命腿", actions: [
    { action: "lianhuan", name: "连环腿" },
  ] },
  "jueqing-bian": { name: "绝情鞭法", actions: [
    { action: "sanwu", name: "三无三不手" },
  ] },
  "liangyi-dao": { name: "两仪刀法", actions: [
    { action: "hebi", name: "双刀合璧" },
    { action: "sanshen", name: "华岳三神峰" },
  ] },
  "liangyi-jian": { name: "两仪剑法", actions: [
    { action: "xunlei", name: "迅雷剑" },
  ] },
  "liuhe-dao": { name: "六合刀", actions: [
    { action: "cross", name: "十字砍" },
    { action: "lianhuan", name: "连环诀" },
    { action: "xiaoyao", name: "逍遥幻影" },
  ] },
  "liumai-shenjian": { name: "六脉神剑", actions: [
    { action: "shangyang", name: "商阳剑" },
    { action: "shaoshang", name: "少商剑" },
    { action: "shaoze", name: "少泽剑" },
    { action: "zhongchong", name: "中冲剑" },
  ] },
  "liuyang-zhang": { name: "六阳掌", actions: [
    { action: "baihong", name: "白虹掌力" },
    { action: "qufu", name: "解生死符" },
    { action: "zhongfu", name: "种生死符" },
  ] },
  "longxiang-banruo": { name: "龙象般若功", actions: [
    { action: "longxiang", name: "龙象之力" },
    { action: "shield", name: "护体神功" },
    { action: "sing", name: "梵唱" },
  ] },
  "longzhua-gong": { name: "龙爪功", actions: [
    { action: "lianhuan", name: "龙爪功连环八式" },
  ] },
  "luoying-shenjian": { name: "落英神剑", actions: [
    { action: "kuangfeng", name: "狂风绝技" },
  ] },
  "meinu-quan": { name: "美女拳法", actions: [
    { action: "wuqing", name: "玉女无情" },
    { action: "youju", name: "古墓幽居" },
  ] },
  "mian-zhang": { name: "绵掌", actions: [
    { action: "huakai", name: "花开并蒂" },
  ] },
  "mo-bang": { name: "墨家棒法", actions: [
    { action: "mo", name: "魔" },
  ] },
  "nianhua-zhi": { name: "拈花指", actions: [
    { action: "fuxue", name: "拈花拂穴" },
  ] },
  "pixie-jian": { name: "辟邪剑法", actions: [
    { action: "cimu", name: "刺目" },
    { action: "ciwan", name: "刺腕" },
    { action: "cixin", name: "刺心" },
    { action: "cizu", name: "刺足" },
    { action: "guimei", name: "鬼魅" },
  ] },
  "quanzhen-jian": { name: "全真剑法", actions: [
    { action: "hubo", name: "双手互搏" },
    { action: "jianhebi", name: "双剑合璧" },
    { action: "lianhuan", name: "三连环" },
    { action: "sanqing", name: "一剑化三清" },
    { action: "tonggui", name: "同归剑法" },
  ] },
  "riyue-bian": { name: "日月鞭法", actions: [
    { action: "chanrao", name: "天缠地绕" },
  ] },
  "ruyi-dao": { name: "如意刀法", actions: [
    { action: "lianhuan", name: "如意连环刀" },
  ] },
  "sanhua-juding": { name: "三花聚顶掌", actions: [
    { action: "sanhua", name: "三花聚顶" },
  ] },
  "sanyin-zhua": { name: "三阴蜈蚣爪", actions: [
    { action: "sanyin", name: "三阴化功" },
    { action: "sayin", name: "三阴化功" },
    { action: "yiji", name: "一击" },
  ] },
  "shiba-pan": { name: "十八盘", actions: [
    { action: "ruhe", name: "岱宗如何" },
  ] },
  "taiji-jian": { name: "太极剑", actions: [
    { action: "chan", name: "缠" },
    { action: "raozhi", name: "绕指柔剑" },
    { action: "shenmen", name: "神门十三剑" },
    { action: "taiji", name: "太极心法" },
    { action: "tongshou", name: "天地同寿" },
  ] },
  "taiji-quan": { name: "太极拳", actions: [
    { action: "luanhuan", name: "乱环诀" },
    { action: "nian", name: "粘" },
  ] },
  "tanzhi-shentong": { name: "弹指神通", actions: [
    { action: "jinglei", name: "弹指惊雷" },
  ] },
  "tianluo-diwang": { name: "天罗地网", actions: [
    { action: "luowang", name: "天罗地网" },
  ] },
  "tianshan-zhang": { name: "天山六阳掌", actions: [
    { action: "feizhang", name: "天山飞杖" },
    { action: "jinxian", name: "大罗金仙化功杖" },
    { action: "pifeng", name: "披风杖" },
  ] },
  "tianyu-qijian": { name: "天羽奇剑", actions: [
    { action: "san", name: "天女散花" },
  ] },
  "xianglong-zhang": { name: "降龙十八掌", actions: [
    { action: "leiting", name: "雷霆降龙" },
    { action: "sanhui", name: "亢龙三悔" },
    { action: "xianglong", name: "降龙一击" },
  ] },
  "xiaohun-zhang": { name: "黯然销魂掌", actions: [
    { action: "xiaohun", name: "黯然销魂掌" },
  ] },
  "xiuluo-dao": { name: "修罗刀法", actions: [
    { action: "xiuluo", name: "修罗无常斩" },
  ] },
  "xue-dao": { name: "血刀刀法", actions: [
    { action: "shendao", name: "祭血神刀" },
  ] },
  "xueshan-jian": { name: "雪山剑法", actions: [
    { action: "liuchu", name: "雪花六出" },
  ] },
  "yanxing-dao": { name: "雁行刀法", actions: [
    { action: "huanying", name: "无形幻影" },
  ] },
  "yinsuo-jinling": { name: "银索金铃", actions: [
    { action: "dian", name: "点穴" },
  ] },
  "yiyang-zhi": { name: "一阳指", actions: [
    { action: "qiankun", name: "一指乾坤" },
  ] },
  "yizhi-chan": { name: "一指禅", actions: [
    { action: "jingmo", name: "惊魔一指" },
  ] },
  "youshen-zhang": { name: "游身八卦掌", actions: [
    { action: "huayu", name: "漫天花雨" },
  ] },
  "yunu-jianfa": { name: "玉女剑法", actions: [
    { action: "hubo", name: "双手互搏" },
    { action: "jianhebi", name: "双剑合璧" },
    { action: "suxin", name: "玉女素心" },
  ] },
  "yuxiao-jian": { name: "玉箫剑法", actions: [
    { action: "jianmang", name: "剑芒" },
    { action: "jianzhi", name: "剑指相配" },
    { action: "jinglei", name: "弹指惊雷" },
  ] },
  "zhemei-shou": { name: "天山折梅手", actions: [
    { action: "zhemei", name: "空手折梅" },
  ] },
  "zui-gun": { name: "醉棍", actions: [
    { action: "zuida", name: "八仙醉打" },
  ] },
};
